# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Configure radian # required as home directory is not saved between builds
    command: |
      echo "options(radian.editing_mode = 'vi')" > ~/.radian_profile
      echo "options(radian.auto_match = FALSE)" >> ~/.radian_profile

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
